### ISSUE TITLE
allow user of migrate.sh to specify an output directory

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.images#14]
At present, [the migrate.sh script](https://github.com/isawnyu/isaw.images/blob/6b50fa68f64e5f068733db1c0226de125864a45c/shell/migrate.sh) captures the second command-line argument to [an internal variable called ```$dest```](https://github.com/isawnyu/isaw.images/blob/6b50fa68f64e5f068733db1c0226de125864a45c/shell/migrate.sh#L146), but that variable does not seem to be subsequently used by the script. Output is governed by [a separate internal variable (```$sitedestdir```)](https://github.com/isawnyu/isaw.images/blob/6b50fa68f64e5f068733db1c0226de125864a45c/shell/migrate.sh#L150), which is calculated to be a string based on the source directory name prefixed with the string "dest". This destination directory is placed in the current working directory at script execution.

I think it would be good if we could specify the output directory by passing an absolute or relative path to the script by way of the second command-line argument.

Does that make sense, @UttaraChavan ?

**Comment by UttaraChavan** [comment]
Tom,
Changed and pushed the script  to shell folder. Please let me know if you need any changes. @paregorios

**Comment by UttaraChavan** [comment]
Tom,

id you check the changes I Made to the script I have replied on your
comment on GitHub as soon as I submitted changes.

Sincerely,
Uttara Chavan

**Comment by paregorios** [comment]
Works! Closing.

**Comment by UttaraChavan** [comment]
You&#8217;ve been invited!

On Airbnb you can discover unique places to stay from local hosts, all over the world.
Simply sign up by May 10, 2015 to get $25 off your first trip of $75 or more.


Claim your $25 credit
http://www.airbnb.com/c/uchavan1?euid=c9b7bb41-59b1-7f68-c3c6-bf6d660a30ef&ri=17673495&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA3MGMyNDlmNDJkOWI2ODdlMWUzMTNiOWFkNGVmODM4MTM1ZGFjYjE4NmIzNDRlOTJjZjAwMDAwMDAxMTEyYTk4Mjk5MmExNjljZTAzZDUyNWU5QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiJjOWI3YmI0MS01OWIxLTdmNjgtYzNjNi1iZjZkNjYwYTMwZWYifQ==&mac=dMNRFEYctFflrh5u206TPzn1qHg=

### Airbnb ###

**Comment by UttaraChavan** [comment]
Remember to claim your credit!

Your friend Uttara gave you $25 to try out Airbnb, a marketplace where you can rent unique, local accommodations, on any budget, anywhere in the world.
You haven't claimed your credit yet - just click below and it will get automatically applied to your first trip!

Minimum booking value $75.

Claim your $25 credit
http://www.airbnb.com/c/uchavan1?euid=8ee9b308-9738-63fd-30ee-76c421cfa30c&ri=17673495&s=1

Thanks,
The Airbnb Team

P.O. Box 410807, San Francisco, CA 94121

Unsubscribe
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA3MGMyNDlmNDJkOWI2ODdlMWUzMTNiOWFkNGVmODM4MTM1ZGFjYjE4NmIzNDRlOTJjZjAwMDAwMDAxMTEyYTk4Mjk5MmExNjljZTAzZDUyNWU5QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbl9yZW1pbmRlciIsInV1aWQiOiI4ZWU5YjMwOC05NzM4LTYzZmQtMzBlZS03NmM0MjFjZmEzMGMifQ==&mac=btI7cOtfurVNDa4V3X4YPakMcAs=

### Airbnb ###
