### ISSUE TITLE
migrate.sh: include hash type in manifest filename

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.images#16]
Right now the script [writes the manifest information on ```manifest.txt```](https://github.com/isawnyu/isaw.images/blob/master/shell/migrate.sh#L29). For [closer adherence to the bagit spec](https://tools.ietf.org/html/draft-kunze-bagit-08#section-2.1.3), let's include the hash algorithm name in the filename of the manifest, like this: ```manifest-sha1.txt```.

**Comment by UttaraChavan** [comment]
Done.

**Comment by paregorios** [comment]
Confirmed. Closing.
