### ISSUE TITLE
migrate.sh: include online filename in manifest, not filepath

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.images#17]
At present, [the script includes the relative path to each file in the manifest file](https://github.com/isawnyu/isaw.images/blob/master/shell/migrate.sh#L28). According to [the bagit spec](https://tools.ietf.org/html/draft-kunze-bagit-08#section-2.1.3), we want only the filename for each file in the manifest file. So, instead of lines like this:
```
9626dcf2f0095b22d8ea13d33f3b1bf422c54104 ../../images-work/scratch//dest/kalabsha/201107061813531/thumb.jpg
```
we want to see lines like this:
```
9626dcf2f0095b22d8ea13d33f3b1bf422c54104 thumb.jpg
```

**Comment by UttaraChavan** [comment]
Done.

**Comment by paregorios** [comment]
Confirmed. Closing.
